### ISSUE TITLE
Issue with One-click install by provider: Redirects to http instead of https

### ISSUE THREAD

**Issue by 3DPixel** [InvoicePlane/InvoicePlane#818] opened 2022-06-17 11:00 UTC
Hi All,

Found a bug (I think)

SSl certificate installed and active on domain.
Hosting provider has a number of one-click install applications including Invoice Plane.

Initial Setup:
- Select sub-directory to install to.
- Install completed successfully.

Primary Setup:
- Link to install directory provided by initial setup e.g http://domain.com/invoiceplane (not https even though control panel URL is secure)
- Manually changed to https://domain.com/invoiceplane
- URL redirects to non-secure site, http...

Only way to complete the setup is to inspect the HTML code and manually change the code to HTTPS then click through the install.

Once install has completed, the login page is presented as a HTTPS page.
After entering login credentials and clicking 'Login', page reverts back to HTTP page and will not proceed as it's not secure.

Solution:
It seems the only way to correct this is to edit the ipconfig.php file and update the base URL.

**Comment by nielsdrost7** [comment] 2022-06-18 08:01
I can't really reproduce this locally since I don't have SSL, but one way to reproduce this is to grab the `master` branch on a server with SSL.
Are you allowed to do the installation without the one-click install?

**Comment by nielsdrost7** [comment] 2022-07-31 12:06
Closing

**Closed by nielsdrost7** 2022-07-31 12:06 UTC
