### ISSUE TITLE
In some cases an amount with a comma in it will not give an error, resulting in SQL Query errors

### ISSUE THREAD

**Issue by UnderDogg** [InvoicePlane/InvoicePlane#745] opened 2021-07-05 15:12 UTC
Somehow it was possible for amounts to contain comma's and will not error out:
```/modules/invoices/models/Mdl_item_amounts.php```
Will result in:
```Column count doesn’t match value count at row 1 - Invalid query: INSERT INTO ip_invoice_item_amounts (item_id, item_subtotal, item_tax_total, item_discount, item_total) VALUES (23, 19, 2,47, 0, 21,47)```

>> The system USES THE LOCALE DECIMAL SIGN (in my case «,» as defined in el_GR locale) IN PLACE OF the standard sql decimal separator «.»

**Comment by oussamadouhou** [comment] 2021-07-05 16:33
You need to use the . (dot) instead

**Comment by UnderDogg** [comment] 2021-07-05 17:01
Yes, I'm aware of that.
- The user on the forum used a comma.
- he tried to save that invoice with a comma in the amount (European style)
- InvoicePlane did not give an error like: "You shouldn't use comma's"
- InvoicePlane in the end gave an SQL error.
This bug report is to prevent that error.

I've asked the user on the forum to give me steps to reproduce, so the bug report can become more clear.

**Comment by UnderDogg** [comment] 2021-07-06 09:51
The user in the forum is using Greek language file.
He says he switched to English and has the same problem.

The user has added the following information:
- Currency Symbol: €
- Currency Code: EUR
- Number Format: 1.000.000,00 European format
- Tax Rate Decimal Places: 2
- 1 client, 2 products categories, 2 products

The user has failed to add the steps:
- Create 1 invoice for the client
- Add line items
- either add a price for the product with a comma 《,》as decimal symbol
- Add that product to the invoice
- or add just a line item with a comma《,》as decimal symbol
See if we can reproduce his error

**Comment by nielsdrost7** [comment] 2023-05-20 14:34
Cannot reproduce the problem, going to close this issue

**Closed by nielsdrost7** 2023-05-20 14:34 UTC
