### ISSUE TITLE
Add ability to reset reports and dashboard at year end 

### ISSUE THREAD

**Issue by msignorello** [InvoicePlane/InvoicePlane#142] opened 2015-01-07 00:48 UTC
This feature should allow the ability to update the dashboard and reporting totals at the end of year. IE: we have closed out of 2014. I want all of my "today" info to be inclusive of my unpaid invoices (unless it is noted as a loss) and anything for 2015 which is current.

This could possibly be achieved by generating the dashboard amounts from the "default invoice group". The only exception with be to include unpaid invoices from the prior year(s)

**Comment by Jadaw1n** [comment] 2015-01-10 13:31
Duplicate of #12

**Closed by Jadaw1n** 2015-01-10 13:31 UTC
Labels: enhancement
