### ISSUE TITLE
Warning: require(vendor/autoload.php) with docker-compose

### ISSUE THREAD

**Issue by Staubgeborener** [InvoicePlane/InvoicePlane#955] opened 2023-07-01 19:26 UTC
## Expected Behavior
Running InvoicePlane local and also access the web overlay only local. So i don't want to use something like http://mydomain.com, but instead http://hostname in my local network.

## Current Behavior
Take a loop to my browser with `http://hostname:port` gives me

```
Warning: require(vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/projects/invoiceplane/index.php on line 18

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/projects/invoiceplane/index.php:18 Stack trace: #0 {main} thrown in /var/www/projects/invoiceplane/index.php on line 18
```

If it helps: I also can't log in on phpmyadmin with "default" credentials (those inside the docker-compose.yml) `ipdevdb:ipdevdb`:
```
 mysqli::real_connect(): (HY000/2002): No such file or directory
 ```

It also doesn't make a difference if i comment out `#` line 1 in `ipconfig.php` or not.

## Steps to Reproduce
Download [latest release](https://github.com/InvoicePlane/InvoicePlane/releases/tag/v1.6.0) and install everything with docker:

```shell
wget https://github.com/InvoicePlane/InvoicePlane/releases/download/v1.6.0/v1.6.0.zip
unzip v1.6.0.zip
cd ./InvoicePlane-1.6.0
docker-compose up -d
cp ipconfig.php.example ipconfig.php
# edit line 8: IP_URL=http://hostname
```

**Comment by kelvin-codes-stuff** [comment] 2023-07-01 19:35
Hi, for the first error: I think you need to run `composer install` in the InvoicePlane root directory.
For the Docker thing, does it give an error? Can you provide more info with this?
For the ipconfig.php file, that has nothing to do with the first error. Comment it out and leave it shut be fine!

**Comment by Staubgeborener** [comment] 2023-07-01 19:41
i think the [MariaDB](https://github.com/InvoicePlane/InvoicePlane/blob/development/docker-compose.yml#L62) part could be the issue @kelvin-codes-stuff 

```
[user@nuc InvoicePlane-1.6.0]$ docker ps -a
CONTAINER ID   IMAGE                                                   COMMAND                  CREATED          STATUS                      PORTS                                                 NAMES
c703d2e161d6   invoiceplane-160_nginx                                  "/docker-entrypoint.…"   18 minutes ago   Up 18 minutes               443/tcp, 0.0.0.0:8083->80/tcp, :::8083->80/tcp        invoiceplane-nginx
453ad22b607a   invoiceplane-160_php                                    "docker-php-entrypoi…"   18 minutes ago   Up 18 minutes               9000/tcp                                              invoiceplane-php
823ed05fc550   invoiceplane-160_phpmyadmin                             "/docker-entrypoint.…"   18 minutes ago   Up 18 minutes               0.0.0.0:8086->80/tcp, :::8086->80/tcp                 invoiceplane-dbadmin
d440f6322ebe   invoiceplane-160_db                                     "docker-entrypoint.s…"   18 minutes ago   Exited (1) 4 seconds ago                                                          invoiceplane-db

[user@nuc InvoicePlane-1.6.0]$ docker logs d440f6322ebe
2023-07-01 19:17:29+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-07-01 19:17:29+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
        command was: mysqld --verbose --help
        /usr/local/bin/docker-entrypoint.sh: line 105: mysqld: command not found
2023-07-01 19:36:06+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.0.2+maria~ubu2204 started.
2023-07-01 19:36:06+00:00 [ERROR] [Entrypoint]: mariadbd failed while attempting to check config
        command was: mysqld --verbose --help
        /usr/local/bin/docker-entrypoint.sh: line 105: mysqld: command not found
```

**Comment by kelvin-codes-stuff** [comment] 2023-07-01 19:44
For the first error not. That error you get when not having the vendor folder by not running `composer install`. I'm pretty sure of that. 

About the Docker error: did you change something in the config files?

**Comment by kelvin-codes-stuff** [comment] 2023-07-01 19:52
Tomorrow I gonna look deeper into it for you! Then I will have also a look at the PHPmyadmin Docker container

**Comment by nielsdrost7** [comment] 2023-07-01 19:54
Support is given on the support forums located at https://community.invoiceplane.com.
As soon as the `vendor` folder is missing, you should run `composer install` just like Kelvin says. Right after that you'll run into the problem that the styles aren't there.
This is the reason why you should use the .zip file.
The `development` repository is for if you want to help with development.

The .zip file conveniently creates the `vendor` folder for you and the styles.

@Staubgeborener 
Open your topic on the support forums regarding your MariaDB problem.
You can also come to slack.
You need to go through some steps to get your MariaDB working.

Closing your support problem. The issues list on github is for reproducible bugs.

**Closed by nielsdrost7** 2023-07-01 19:54 UTC
