### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by mbsarino** [InvoicePlane/InvoicePlane#163] opened 2015-01-28 09:32 UTC
Is there a way for me to change the field type of a specific custom field?  I'd like to make one of my custom fields a text area.

Also, what is the correct syntax for showing showing a particular custom field input in a specific part of a page.  All custom fields appear in one block on the page as of now.

**Comment by Kovah** [comment] 2015-01-28 13:48
You would have to edit this directly in the layouts everywhere where your custom field should show up.
If you want to have the custom fields elsewhere you can try to copy the code that displays the field.

Duplicate of #46

**Closed** 2015-01-28 18:30 UTC
Labels: duplicate

**Comment by mbsarino** [comment] 2015-01-28 18:34
I have tried copying the code but get all sorts of PHP errors.  Pretty much why I was hoping for help with the syntax.

**Comment by Kovah** [comment] 2015-01-28 19:02
What exactly do you want to change?

**Comment by mbsarino** [comment] 2015-01-29 03:05
I just need the field in this image to be a text area field.  
![capture - ip fields](https://cloud.githubusercontent.com/assets/7676572/5951773/5b0ed0ee-a79e-11e4-8240-7d64efc3b5a7.JPG)

**Comment by Kovah** [comment] 2015-01-29 13:22
Could you paste the code of this field here?

**Comment by mbsarino** [comment] 2015-01-29 15:37
Hdere is the code:

<?php foreach ($custom_fields as $custom_field) { ?>
                <label><?php echo $custom_field->custom_field_label; ?></label>
                <input type="text-area" class="form-control"
                       name="custom[<?php echo $custom_field->custom_field_column; ?>]"
                       id="<?php echo $custom_field->custom_field_column; ?>"
                       value="<?php echo form_prep($this->mdl_invoices->form_value('custom[' . $custom_field->custom_field_column . ']')); ?>">
            <?php } ?>

**Comment by mbsarino** [comment] 2015-01-30 10:46
@Kovah : any updates on this?

**Comment by Kovah** [comment] 2015-01-30 16:05
I could need input name of the custom field which should be displayed as a textarea. (`<input name="customXYZ" ...`)

**Comment by mbsarino** [comment] 2015-01-30 19:23
The field name is "invoice_custom_details_summary".
