### ISSUE TITLE
Problem with mPDF

### ISSUE THREAD

**Issue by Tiebienotjuh** [InvoicePlane/InvoicePlane#806] opened 2022-03-11 18:11 UTC
Hi,

I'm changed InvoicePlane from directory.
Only i got problems with mpdf.

I get this error and i tried everything.
`An uncaught Exception was encountered
Type: Mpdf\MpdfException

Message: Temporary files directory "/home/tiebe/domains/tiebienotjuh.com/public_html/heikkibike/vendor/mpdf/mpdf/src/Config/../../tmp" is not writable

Filename: /home/tiebe/domains/tiebienotjuh.com/public_html/heikkibike/vendor/mpdf/mpdf/src/Cache.php

Line Number: 17

Whats the best solution to fix it?

**Comment by UnderDogg** [comment] 2022-03-12 05:38
1) remove personal information from your opening post. We don't need to know the full path to your public_html directory

2) The problem is in the following error:
```Message: Temporary files directory "/home/path/to/public_html/(invoiceplane_directory)/vendor/mpdf/mpdf/src/Config/../../tmp" is not writable```

And that means that you cannot write to that directory.
If you solve that, your problem with mPDF might be solved

**Comment by Tiebienotjuh** [comment] 2022-03-12 12:24
Hey! I understand that he cannot write this directory but the problem is this is an exact copy of invoiceplane on another domain and the directory mentioned does not exist at all. On the other domain there is no problem.

**Comment by UnderDogg** [comment] 2022-03-13 04:22
Hey, I understand that, but look at the error message.

It's a copy and on that other location IP might be installed in a less-deeper directory.

Now it's the time to reproduce your problem locally and maybe find a solution there.

One of the solutions will be `composer install`. It will re-generate the autoloader class which holds the locations of all the classes, so it might find better your `tmp` directory.

Normally ... I install invoiceplane and I don't copy it.

**Comment by nielsdrost7** [comment] 2022-07-31 12:02
Sorry, closing this. Take a look at my solution of March 13th

**Closed by nielsdrost7** 2022-07-31 12:02 UTC
Labels: Support
