### ISSUE TITLE
Mark paid invoce doesn't  set Payment

### ISSUE THREAD

**Issue by DavorSaric** [InvoicePlane/InvoicePlane#166] opened 2015-01-28 18:39 UTC
Hi,

don't know is this really a bug or is ment like that by the system but  when marking invoice as paid it doesn't put in Dashbord  - Invoice Overview as paid SUM, no entry. If it's marked as sent or draft or viewed the corresponding entry SUM is statused in Dashboard. Maybe this isn't really a bug because if I go to payments and then enter payment then the status in Invoice Overview  SUM is show. Maybe marking invoice as paid status should automatically enter payment?

Version 1.1.2.

**Comment by Kovah** [comment] 2015-01-30 16:14
To sum up:
1. You have an invoice you marked as paid.
2. The `Paid` sum on the dashboard does not change.
Is that right?

About the payments: payments do not change anything about sums on the dashbord, they are only using invoices to calculate the sums.

**Comment by stobbsm** [comment] 2015-01-30 17:35
It seems to me that marking an invoice as paid, but not processing an actual payment in the system, it should not change the ```Paid``` sum.

If you process a payment, it should mark the invoice paid by default, but manually marking it paid without processing a payment may cause undesired behaviour.

The process should be:
1. Have an invoice that is not yet paid.
2. Process payment using the "Make Payment" option.
3. The ```Paid``` sum changes.

ps. I am alive, and getting back on the mend finally. Will get to work on some of the outstanding issues ASAP.

**Comment by AbbyNormal** [comment] 2015-01-30 17:40
@ Kovah
1. Yes,
2. yes, the Paid sum doesn't change if you mark the invoice as paid.

BUT as stobbsm said I think this is not a bug, just a difference in concepts. Maybe the invoices should not have a "Mark as paid option" at all. Because marking them as paid should be only possible through payments. Do you agree?

**Closed** 2021-06-10 12:38 UTC
