### ISSUE TITLE
[Need to reproduce] No user created after Installation - ip_users is blank

### ISSUE THREAD

**Issue by devnull-hub-lab** [InvoicePlane/InvoicePlane#954] opened 2023-06-28 21:54 UTC
Hi guys,

It seems, no user is created after invoice plane installation.
I checked ip_users table and it is blank.

Invoice Log apparently is fine.

But something is so strange. After create a user (email and informations), the invoice plane page returns to setup page again (language, prerequisites, database details...). Everything is repeating by 2 or 3 times, except create user page.

Nothing strange in access.log/error.log in apache.

I found similar issue in https://community.invoiceplane.com/t/cant-login-after-installation/2027 , but without solution.

Can I check something?

Thanks in advance!

## Environment
Invoice Plane 1.6.0
FreeBSD 13.2
MariaDB 10.5.2
Apache 2.4.57
PHP 8.1

## Failure Logs
[invoice.txt](https://github.com/InvoicePlane/InvoicePlane/files/11900139/invoice.txt)

**Comment by nielsdrost7** [comment] 2023-06-28 22:06
I sooooo wished you would have posted this on the forums, but ok:
- The steps to reproduce are clear, but now we need to reproduce the problem.
- Once the problem is reproduced, we can resolve it.

- Did you use the .zip file or did you clone the development branch?
- Is there a way you can create a docker environment right before you encounter the problem?
- with that docker environment we should be able to reproduce the problem
- Did you create fresh database? (comes from that old forum topic)

**Comment by nielsdrost7** [comment] 2023-06-28 22:20
The only things I can think of at the moment is:
- it's an apache server. It's also an apache server in that old forum thread.
- `if ($this->mdl_users->run_validation()) {` in `application/modules/setup/controllers/Setup.php`, so we need to log more, to see if validation failed

**Comment by devnull-hub-lab** [comment] 2023-06-28 22:24
@ nielsdrost7, thanks for your reply!
If the forum is the right place for this, please forgive me. So, I can close this issue.

I also found in forum similar issues, like these:
https://community.invoiceplane.com/t/topic/2582/3
https://community.invoiceplane.com/t/topic/10281

- I use the .zip file, downloaded from https://invoiceplane.com/support

- Unfortunately I can't use docker. Docker is for linux systems, don't run in FreeBSD.
- But I can use Jail (similar docker concept) that I can isolate my environment.

- Yes, I created a fresh database:
CREATE DATABASE invoice;
GRANT ALL ON invoice.* TO 'admin_invoice'@'localhost' IDENTIFIED BY 'MYPASSWD';
FLUSH PRIVILEGES;

**Comment by nielsdrost7** [comment] 2023-06-28 22:29
Ok, let's leave this one open for now, it's fine.
We'll just have to reproduce the issue, that's all.

If you want, you can create your user in the database. That way you can keep going with your current setup.

We'll take a look this weekend to see if the issue is reproducible

**Comment by devnull-hub-lab** [comment] 2023-06-28 22:37
@nielsdrost7 I will try to create manually user in ip_users table.
This instruction from https://community.invoiceplane.com/t/topic/220/3 to manually create a user are correct?

I will create a new jail just for this test. In a jail, if I can reproduce, I even can give you ssh access to it if necessary, it is a completely isolated environment from the main host.

**Comment by nielsdrost7** [comment] 2023-06-28 22:40
Yep, those are correct, but please change password afterwards

**Comment by kelvin-codes-stuff** [comment] 2023-06-29 05:42
Hi @devnull-hub-lab
i'm gonna look into this to try to replicate this. Would you mind to zip you're current installation in a ZIP file and share it with me? 

Also would you mind to enable debugging and try to create a user again? And then have a look into the logs, maybe there will be more info. This can be done to edit ipconfig.php. On line 11 set `ENABLE_DEBUG` to `true`

**Comment by devnull-hub-lab** [comment] 2023-06-29 17:22
Hi @kelvin-codes-stuff 
Yes, sure.
Please download it at https://apt322.org/invoice_aftersetup.tar.gz

Don't worry about user/passwd to be expose, it is a test environment.

The log file attached with this issue is already with ENABLE_DEBUG=true

An important thing (I guess), after setup, "ENCRYPTION_KEY" in ipconfig.php remains blank.

Tonight I will do more tests using nginx instead apache. So I can tell you if it's something related to apache or not.

**Comment by kelvin-codes-stuff** [comment] 2023-06-29 18:19
Hi, im happy it now works! If it isn't the production, can you share the `ipconfig.php` here? Maybe there is something wrong there

**Comment by devnull-hub-lab** [comment] 2023-06-29 18:26
It worked temporary with this workaround, however it would not be wise to keep PHP DEBUG active in a production environment. Without php debug, the problem persist.

My ipconfig.php:

`#<?php exit('No direct script access allowed'); ?>
# InvoicePlane Configuration File

### START HERE
# Set your URL without trailing slash here, e.g. http://your-domain.com
# If you use a subdomain, use http://subdomain.your-domain.com
# If you use a subfolder, use http://your-domain.com/subfolder
IP_URL=https://apt322.org/invoice

# Having problems? Enable debug by changing the value to 'true' to enable advanced logging
ENABLE_DEBUG=true

# Set this setting to 'true' if you want to disable the setup for security purposes
DISABLE_SETUP=false

# To remove index.php from the URL, set this setting to 'true'.
# Please notice the additional instructions in the htaccess file!
REMOVE_INDEXPHP=false

# These database settings are set during the initial setup
DB_HOSTNAME=127.0.0.1
DB_USERNAME=admin_invoice
DB_PASSWORD=N2Y1ZWY4Nzk4MjRh
DB_DATABASE=invoice
DB_PORT=3306

# If you want to be logged out after closing your browser window, set this setting to 0 (ZERO).
# The number represents the amount of minutes after that IP will automatically log out users,
# the default is 10 days.
SESS_EXPIRATION=864000

# Enable the deletion of invoices
ENABLE_INVOICE_DELETION=false

# Disable the read-only mode for invoices
DISABLE_READ_ONLY=false

##
## DO NOT CHANGE ANY CONFIGURATION VALUES BELOW THIS LINE!
## =======================================================
##

# This key is automatically set after the first setup. Do not change it manually!
ENCRYPTION_KEY=
ENCRYPTION_CIPHER=AES-256

# Set to true after the initial setup
SETUP_COMPLETED=true`

**Comment by kelvin-codes-stuff** [comment] 2023-06-29 18:37
@devnull-hub-lab  So i changed the db info to be a string. Resolves this the issue? 
https://pastebin.com/QUnGYGcB

**Comment by devnull-hub-lab** [comment] 2023-06-29 18:54
@kelvin-codes-stuff , all changed db info with simple quotes, but not solves the issue.

`DB_HOSTNAME='127.0.0.1'
DB_USERNAME='admin_invoice'
DB_PASSWORD='N2Y1ZWY4Nzk4Mj'
DB_DATABASE='invoice'`

**Comment by kelvin-codes-stuff** [comment] 2023-06-29 19:07
Could you try to remove the `ipconfig.php` and then copy `ipconfig.php.example` to `ipconfig.php`. Then fill in app URL? You will see the setup page after a refresh, you can click through it (it wil not ask for a user because DB already excist). Hope that this will help

**Comment by devnull-hub-lab** [comment] 2023-06-29 20:46
@kelvin-codes-stuff I did this, but without php debug set, the setup page appears many times, like it's in a loop.

I think I found the problem, but I can't identify why.

The first line of ipconfig.php is causing the issue.
#<?php exit('No direct script access allowed'); ?>

This comment # is causing the issue.
If I remove entire line, the issue is solved.
OR if I include one space after #, the problem is solved as well

# <?php exit('No direct script access allowed'); ?>
instead of:
#<?php exit('No direct script access allowed'); ?>

Does that make any sense to you?

**Comment by kelvin-codes-stuff** [comment] 2023-06-29 21:09
@devnull-hub-lab i also can't tell why atm, but at least its solved.
If you change `SETUP_COMPLETED` to `true` you will get out of the setup loop!

**Comment by devnull-hub-lab** [comment] 2023-06-29 21:25
@kelvin-codes-stuff thanks!

Close this issue? Or will something be investigated?

If I see someone having this problem, I will suggest that they put a space after # on the first line.
I don't know if it would be interesting to put this note in the installation documentation. It's up to you.

But if you need something to test, please let me know, I'm free to help.

Thanks again to you and @nielsdrost7!

**Comment by nielsdrost7** [comment] 2023-06-30 02:38
Glad it's solved, guys, I'm closing the issue

**Closed by nielsdrost7** 2023-06-30 02:38 UTC
Labels: Bug, future-versions
